**Main sources:**

https://github.com/grantsrb/Gym-Snake

https://www.youtube.com/watch?v=5Vy5Dxu7vDs

https://github.com/nicknochnack/OpenAI-Reinforcement-Learning-with-Custom-Environment/blob/main/OpenAI%20Custom%20Environment%20Reinforcement%20Learning.ipynb

In [123]:
from gym import Env
from gym.spaces import Discrete, Box
import numpy as np
import random

# Create snake environment

In [243]:
class SnakeEnv(Env):
    def __init__(self):
        pass
        
    def step(self, action):
        pass

    def render(self):
        pass
    
    def reset(self):
        pass
#         return self.state
    

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [ ]:
class Controller():
    
    def __init__(self):
        self.grid = Grid()
        self.snake = Snake()
        self.done = False
    
    def step(self):
        # move snake
        snake.move(action)

        # check death
        if env.check_death(snake):
            self.done = True
            reward = -20

        # check reward (delete tail if no reward) + (palce food if food eaten)
        if env.check_food_eaten(snake):
            reward = 10
            env.place_food()
        else:
            reward = 0
            snake.pop_tail()

        # get state
        self.state = env.get_state()
    
#         return self.state, reward, done, info
    
    def get_state():
        
        state = np.zeros(12, dtype=np.uint8)
        
        # Get direction
        direction = self.snake.direction
        state[direction] = 1
        
        # Get food direction
        food_relative_to_head = env.get_food_dir(snake) # returns [0,0,1,1]
        
        
#       need to return (moving direction, 0, 1, 2, 3; UP, DOWN, LEFT, RIGHT
#                       reward direction, 0, 1, 2, 3; UP, DOWN, LEFT, RIGHT
#                       danger, 0, 1, 2; STRAIGHT, LEFT, RIGHT) 
        
        

In [277]:
class Grid():
    
    BODY_COLOR  = np.array([1,0,0], dtype=np.uint8)
    HEAD_COLOR  = np.array([255, 0, 0], dtype=np.uint8)
    FOOD_COLOR  = np.array([3,0,255], dtype=np.uint8)
    SPACE_COLOR = np.array([0,255,0], dtype=np.uint8)
    WALL_COLOR  = np.array([5,100,0], dtype=np.uint8)
    
    def __init__(self, grid_size=[30,30], unit_size=10, unit_gap=1):
        
        self.grid_size = np.asarray(grid_size, dtype=np.int)
        self.height = self.grid_size[0]
        self.width = self.grid_size[1]
        
        self.grid = np.zeros((self.height, self.width, 3), dtype=np.uint8)
        self.grid[:,:,:]  = self.SPACE_COLOR
        self.grid[:,0,:]  = self.WALL_COLOR
        self.grid[:,-1,:] = self.WALL_COLOR
        self.grid[0,:,:]  = self.WALL_COLOR
        self.grid[-1,:,:] = self.WALL_COLOR
    
    def get_color(self, coor):
        return self.grid[coor[0], coor[1], :]
    
    def check_death(self, Snake_c):
        
        # where snake wants to go
        square_color = get_color(Snake_c.head)
        
        # head in wall or in body
        if square_color == self.WALL_COLOR or square_color == self.BODY_COLOR:
            return True
        
    def check_food_eaten(self, Snake_c):
        
        # where snake wants to go
        square_color = get_color(Snake_c.head)
        
        # head in wall or in body
        if square_color == self.FOOD_COLOR:
            return True
        
#     def place_food(self, coor):
#         # check if space is empty - while true
#         self.grid[coor[0], coor[1], :] = self.FOOD_COLOR

    def place_food_random(self):
        
        while True:
            new_x = np.random.randint(1, self.height-1)
            new_y = np.random.randint(1, self.width-1)
            
            if np.array_equal(self.grid[new_x, new_y, :], self.SPACE_COLOR):
                #place food
                self.grid[new_x, new_y, :] = self.FOOD_COLOR
                break
        
    def erase_cell(self, coor):
        self.grid[coor[0], coor[1], :] = self.SPACE_COLOR
        
    def draw_snake(self, Snake_c):
        head = Snake_c.head
        body = Snake_c.body
        
        # draw head
        self.grid[head[0], head[1], :] = self.HEAD_COLOR
        #draw body
        for coor in body:
            self.grid[coor[0], coor[1], :] = self.BODY_COLOR
            
    def get_food_direction(self, Snake_c):
        # reward direction, 0, 1, 2, 3; UP, DOWN, LEFT, RIGHT
        
        head = Snake_c.haed
        
        # X coor <- get UP or DOWN or SAME LEVEL
#         if head[0] <
            
        
        

In [378]:
class Snake():
    
    UP = 0
    DOWN = 1
    LEFT = 2
    RIGHT = 3
    
    def __init__(self, init_coor=[4,2], init_len=3):
        # note: possible to initialize with error, leave defaults for now
        self.head = init_coor
        self.direction = self.DOWN
        self.body = list()
        for i in reversed(range(1,init_len)):
            self.body.append([self.head[0]-i, self.head[1]])
            
        
    def move(self, action):
        #ACTIONS
        # straight = 0
        # left = 1
        # right = 2

        # GET NEXT DIRECTION FROM ACTION
        clock_wise_dir = [self.UP, self.RIGHT, self.DOWN, self.LEFT]
        curr_dir_idx = clock_wise_dir.index(self.direction)

        #no turn
        if action == 0:
            next_dir = self.direction #no change
        # left turn
        elif action == 1:
            next_dir = clock_wise_dir[curr_dir_idx - 1] % 4  # -1%4=3, so we go to the other end of list
        # right turn
        elif action == 2:
            next_dir = clock_wise_dir[curr_dir_idx + 1] % 4  # 4%4=0, so we go to the other end of list
        
        # update the direction
        self.direction = next_dir

        # EXECUTE TURN
        # add head to body
        self.body.append(self.head.copy())

        # move head
        if next_dir == self.UP:
            self.head[0] -= 1  #remember top left is [0,0]
        elif next_dir == self.DOWN:
            self.head[0] += 1
        elif next_dir == self.RIGHT:
            self.head[1] += 1
        elif next_dir == self.LEFT:
            self.head[1] -= 1

    # removes the last element from the body
    def pop_tail(self):
        self.body.pop(0)
                
        


In [379]:
env = Grid(grid_size=[10,10])
snake = Snake()

In [380]:
snake.head

[4, 2]

In [381]:
snake.body

[[2, 2], [3, 2]]

In [382]:
env.draw_snake(snake)
env.place_food_random()
env.grid[:,:,0]

array([[  5,   5,   5,   5,   5,   5,   5,   5,   5,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   1,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   1,   3,   0,   0,   0,   0,   0,   5],
       [  5,   0, 255,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   5,   5,   5,   5,   5,   5,   5,   5,   5]], dtype=uint8)

In [383]:
snake.move(1)

In [384]:
snake.head

[4, 3]

In [385]:
snake.body

[[2, 2], [3, 2], [4, 2]]

In [386]:
env.erase_cell(snake.body[0])
snake.pop_tail()
env.draw_snake(snake)
env.grid[:,:,0]

array([[  5,   5,   5,   5,   5,   5,   5,   5,   5,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   1,   3,   0,   0,   0,   0,   0,   5],
       [  5,   0,   1, 255,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   0,   0,   0,   0,   0,   0,   0,   0,   5],
       [  5,   5,   5,   5,   5,   5,   5,   5,   5,   5]], dtype=uint8)

# Create agent

# Train

# Test agent